Experiment No.15

Name:Pranav Menon\
Batch : ENTC - B1\
PRN No. : 25070123085

Aim of the experiment : Data Normalization and Data Type Conversion

In [33]:
# Dataset Creation

import pandas as pd
import numpy as np

data = {
    'Product' : ['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
    'Price' : [55000,20000,30000,2000,8000,45000],
    'Units Sold' : [25,60,35,80,50,15],
    'Discount' : [10,15,12,20,10,0]
}
df = pd.DataFrame(data)
print(df)

      Product  Price  Units Sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          60        15
2      Tablet  30000          35        12
3  Headphones   2000          80        20
4  Smartwatch   8000          50        10
5      Camera  45000          15         0

In [34]:
# Min - Max Normalisation
# Min - Max Normalisation for Price

df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())
print(df[['Product','Price','Price_MinMax']])

      Product  Price  Price_MinMax
0      Laptop  55000      1.000000
1      Mobile  20000      0.339623
2      Tablet  30000      0.528302
3  Headphones   2000      0.000000
4  Smartwatch   8000      0.113208
5      Camera  45000      0.811321

In [35]:
# Normalise Multiple Columns

cols=['Price','Units Sold','Discount']
df_norm = (df[cols]-df[cols].min())/(df[cols].max() - df[cols].min())
print(df_norm)

      Price  Units Sold  Discount
0  1.000000    0.153846      0.50
1  0.339623    0.692308      0.75
2  0.528302    0.307692      0.60
3  0.000000    1.000000      1.00
4  0.113208    0.538462      0.50
5  0.811321    0.000000      0.00

In [36]:
# Z-Score Normalisation

df['Units ZScore'] = (df['Units Sold'] - df['Units Sold'].mean()) / df['Units Sold'].std()
print(df[['Product','Units Sold','Units ZScore']])

      Product  Units Sold  Units ZScore
0      Laptop          25     -0.799885
1      Mobile          60      0.660775
2      Tablet          35     -0.382554
3  Headphones          80      1.495437
4  Smartwatch          50      0.243443
5      Camera          15     -1.217216

In [37]:
# Decimal Scaling

df['Price_Decimal'] = df['Price'] / 100000
print(df[['Product','Price','Price_Decimal']])

      Product  Price  Price_Decimal
0      Laptop  55000           0.55
1      Mobile  20000           0.20
2      Tablet  30000           0.30
3  Headphones   2000           0.02
4  Smartwatch   8000           0.08
5      Camera  45000           0.45

In [38]:
# Decimal Scaling

df['Units_Decimal'] = df['Units Sold'] / 100
print(df[['Product','Price','Units_Decimal']])

      Product  Price  Units_Decimal
0      Laptop  55000           0.25
1      Mobile  20000           0.60
2      Tablet  30000           0.35
3  Headphones   2000           0.80
4  Smartwatch   8000           0.50
5      Camera  45000           0.15

In [39]:
# Decimal Scaling

df['Discounts_Decimal'] = df['Discount'] / 100
print(df[['Product','Price','Discounts_Decimal']])

      Product  Price  Discounts_Decimal
0      Laptop  55000               0.10
1      Mobile  20000               0.15
2      Tablet  30000               0.12
3  Headphones   2000               0.20
4  Smartwatch   8000               0.10
5      Camera  45000               0.00

In [40]:
# Data Creation

import pandas as pd
import numpy as np
data = {
'Order_ID':[101,102,103,104,105,106],
'Customer_Gender':['Male','Female','Female','Male','Female','Male'],
'Payment_Method':['UPI','Credit Card','Debit Card','COD','UPI','Debit Card'],
'Product_Category':['Electronics','Clothing','Home','Electronics','Beauty','Electronics'],
'City':['Pune','Mumbai','Delhi','Bangalore','Pune','Hyderabad'],
'Order_Value':[4500,2300,3200,5200,1800,4100]
}

df = pd.DataFrame(data)

print(df)

   Order_ID Customer_Gender Payment_Method Product_Category       City  \
0       101            Male            UPI      Electronics       Pune
1       102          Female    Credit Card         Clothing     Mumbai
2       103          Female     Debit Card             Home      Delhi
3       104            Male            COD      Electronics  Bangalore
4       105          Female            UPI           Beauty       Pune
5       106            Male     Debit Card      Electronics  Hyderabad

   Order_Value
0         4500
1         2300
2         3200
3         5200
4         1800
5         4100

In [41]:
# Label Encoding

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender_Label'] = le.fit_transform(df['Customer_Gender'])
df

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Gender_Label
0,101,Male,UPI,Electronics,Pune,4500,1
1,102,Female,Credit Card,Clothing,Mumbai,2300,0
2,103,Female,Debit Card,Home,Delhi,3200,0
3,104,Male,COD,Electronics,Bangalore,5200,1
4,105,Female,UPI,Beauty,Pune,1800,0
5,106,Male,Debit Card,Electronics,Hyderabad,4100,1

In [42]:
# Label Encoding

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Payment_Method_Label'] = le.fit_transform(df['Payment_Method'])
df

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Gender_Label,Payment_Method_Label
0,101,Male,UPI,Electronics,Pune,4500,1,3
1,102,Female,Credit Card,Clothing,Mumbai,2300,0,1
2,103,Female,Debit Card,Home,Delhi,3200,0,2
3,104,Male,COD,Electronics,Bangalore,5200,1,0
4,105,Female,UPI,Beauty,Pune,1800,0,3
5,106,Male,Debit Card,Electronics,Hyderabad,4100,1,2

In [43]:
# Label Encoding

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Product_Category_Label'] = le.fit_transform(df['Product_Category'])
df

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Gender_Label,Payment_Method_Label,Product_Category_Label
0,101,Male,UPI,Electronics,Pune,4500,1,3,2
1,102,Female,Credit Card,Clothing,Mumbai,2300,0,1,1
2,103,Female,Debit Card,Home,Delhi,3200,0,2,3
3,104,Male,COD,Electronics,Bangalore,5200,1,0,2
4,105,Female,UPI,Beauty,Pune,1800,0,3,0
5,106,Male,Debit Card,Electronics,Hyderabad,4100,1,2,2

In [44]:
# Label Encoding

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['City_Label'] = le.fit_transform(df['City'])
df

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Gender_Label,Payment_Method_Label,Product_Category_Label,City_Label
0,101,Male,UPI,Electronics,Pune,4500,1,3,2,4
1,102,Female,Credit Card,Clothing,Mumbai,2300,0,1,1,3
2,103,Female,Debit Card,Home,Delhi,3200,0,2,3,1
3,104,Male,COD,Electronics,Bangalore,5200,1,0,2,0
4,105,Female,UPI,Beauty,Pune,1800,0,3,0,4
5,106,Male,Debit Card,Electronics,Hyderabad,4100,1,2,2,2

In [45]:
# One - Hot Coding

df_encoded = pd.get_dummies(df,columns=['Payment_Method'])
df_encoded

,Order_ID,Customer_Gender,Product_Category,City,Order_Value,Gender_Label,Payment_Method_Label,Product_Category_Label,City_Label,Payment_Method_COD,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI
0,101,Male,Electronics,Pune,4500,1,3,2,4,False,False,False,True
1,102,Female,Clothing,Mumbai,2300,0,1,1,3,False,True,False,False
2,103,Female,Home,Delhi,3200,0,2,3,1,False,False,True,False
3,104,Male,Electronics,Bangalore,5200,1,0,2,0,True,False,False,False
4,105,Female,Beauty,Pune,1800,0,3,0,4,False,False,False,True
5,106,Male,Electronics,Hyderabad,4100,1,2,2,2,False,False,True,False

In [46]:
# One - Hot Coding

df_encoded = pd.get_dummies(df,columns=['Customer_Gender'])
df_encoded

,Order_ID,Payment_Method,Product_Category,City,Order_Value,Gender_Label,Payment_Method_Label,Product_Category_Label,City_Label,Customer_Gender_Female,Customer_Gender_Male
0,101,UPI,Electronics,Pune,4500,1,3,2,4,False,True
1,102,Credit Card,Clothing,Mumbai,2300,0,1,1,3,True,False
2,103,Debit Card,Home,Delhi,3200,0,2,3,1,True,False
3,104,COD,Electronics,Bangalore,5200,1,0,2,0,False,True
4,105,UPI,Beauty,Pune,1800,0,3,0,4,True,False
5,106,Debit Card,Electronics,Hyderabad,4100,1,2,2,2,False,True

In [47]:
# One - Hot Coding

df_encoded = pd.get_dummies(df,columns=['Product_Category'])
df_encoded

,Order_ID,Customer_Gender,Payment_Method,City,Order_Value,Gender_Label,Payment_Method_Label,Product_Category_Label,City_Label,Product_Category_Beauty,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home
0,101,Male,UPI,Pune,4500,1,3,2,4,False,False,True,False
1,102,Female,Credit Card,Mumbai,2300,0,1,1,3,False,True,False,False
2,103,Female,Debit Card,Delhi,3200,0,2,3,1,False,False,False,True
3,104,Male,COD,Bangalore,5200,1,0,2,0,False,False,True,False
4,105,Female,UPI,Pune,1800,0,3,0,4,True,False,False,False
5,106,Male,Debit Card,Hyderabad,4100,1,2,2,2,False,False,True,False

In [48]:
df_encoded = pd.get_dummies(df,columns=['City'])
df_encoded

,Order_ID,Customer_Gender,Payment_Method,Product_Category,Order_Value,Gender_Label,Payment_Method_Label,Product_Category_Label,City_Label,City_Bangalore,City_Delhi,City_Hyderabad,City_Mumbai,City_Pune
0,101,Male,UPI,Electronics,4500,1,3,2,4,False,False,False,False,True
1,102,Female,Credit Card,Clothing,2300,0,1,1,3,False,False,False,True,False
2,103,Female,Debit Card,Home,3200,0,2,3,1,False,True,False,False,False
3,104,Male,COD,Electronics,5200,1,0,2,0,True,False,False,False,False
4,105,Female,UPI,Beauty,1800,0,3,0,4,False,False,False,False,True
5,106,Male,Debit Card,Electronics,4100,1,2,2,2,False,False,True,False,False

In [49]:
# One - Hot Coding

df_encoded = pd.get_dummies(df,columns=['Order_Value'])
df_encoded

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Gender_Label,Payment_Method_Label,Product_Category_Label,City_Label,Order_Value_1800,Order_Value_2300,Order_Value_3200,Order_Value_4100,Order_Value_4500,Order_Value_5200
0,101,Male,UPI,Electronics,Pune,1,3,2,4,False,False,False,False,True,False
1,102,Female,Credit Card,Clothing,Mumbai,0,1,1,3,False,True,False,False,False,False
2,103,Female,Debit Card,Home,Delhi,0,2,3,1,False,False,True,False,False,False
3,104,Male,COD,Electronics,Bangalore,1,0,2,0,False,False,False,False,False,True
4,105,Female,UPI,Beauty,Pune,0,3,0,4,True,False,False,False,False,False
5,106,Male,Debit Card,Electronics,Hyderabad,1,2,2,2,False,False,False,True,False,False

In [50]:
# Dummy Coding

df_encoded = pd.get_dummies(df,columns=['Payment_Method'],drop_first=True)
df_encoded

,Order_ID,Customer_Gender,Product_Category,City,Order_Value,Gender_Label,Payment_Method_Label,Product_Category_Label,City_Label,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI
0,101,Male,Electronics,Pune,4500,1,3,2,4,False,False,True
1,102,Female,Clothing,Mumbai,2300,0,1,1,3,True,False,False
2,103,Female,Home,Delhi,3200,0,2,3,1,False,True,False
3,104,Male,Electronics,Bangalore,5200,1,0,2,0,False,False,False
4,105,Female,Beauty,Pune,1800,0,3,0,4,False,False,True
5,106,Male,Electronics,Hyderabad,4100,1,2,2,2,False,True,False

In [51]:
# Dummy Coding

df_encoded = pd.get_dummies(df,columns=['Customer_Gender'],drop_first=True)
df_encoded

,Order_ID,Payment_Method,Product_Category,City,Order_Value,Gender_Label,Payment_Method_Label,Product_Category_Label,City_Label,Customer_Gender_Male
0,101,UPI,Electronics,Pune,4500,1,3,2,4,True
1,102,Credit Card,Clothing,Mumbai,2300,0,1,1,3,False
2,103,Debit Card,Home,Delhi,3200,0,2,3,1,False
3,104,COD,Electronics,Bangalore,5200,1,0,2,0,True
4,105,UPI,Beauty,Pune,1800,0,3,0,4,False
5,106,Debit Card,Electronics,Hyderabad,4100,1,2,2,2,True

In [52]:
# Dummy Coding

df_encoded = pd.get_dummies(df,columns=['Product_Category'],drop_first=True)
df_encoded

,Order_ID,Customer_Gender,Payment_Method,City,Order_Value,Gender_Label,Payment_Method_Label,Product_Category_Label,City_Label,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home
0,101,Male,UPI,Pune,4500,1,3,2,4,False,True,False
1,102,Female,Credit Card,Mumbai,2300,0,1,1,3,True,False,False
2,103,Female,Debit Card,Delhi,3200,0,2,3,1,False,False,True
3,104,Male,COD,Bangalore,5200,1,0,2,0,False,True,False
4,105,Female,UPI,Pune,1800,0,3,0,4,False,False,False
5,106,Male,Debit Card,Hyderabad,4100,1,2,2,2,False,True,False

In [53]:
# Dummy Coding

df_encoded = pd.get_dummies(df,columns=['City'],drop_first=True)
df_encoded

,Order_ID,Customer_Gender,Payment_Method,Product_Category,Order_Value,Gender_Label,Payment_Method_Label,Product_Category_Label,City_Label,City_Delhi,City_Hyderabad,City_Mumbai,City_Pune
0,101,Male,UPI,Electronics,4500,1,3,2,4,False,False,False,True
1,102,Female,Credit Card,Clothing,2300,0,1,1,3,False,False,True,False
2,103,Female,Debit Card,Home,3200,0,2,3,1,True,False,False,False
3,104,Male,COD,Electronics,5200,1,0,2,0,False,False,False,False
4,105,Female,UPI,Beauty,1800,0,3,0,4,False,False,False,True
5,106,Male,Debit Card,Electronics,4100,1,2,2,2,False,True,False,False

In [54]:
import pandas as pd

df = pd.read_csv('/content/amazon_products_dataset.csv')
df

   Product_ID                 Product_Name  Price  Rating  Reviews  Units_Sold
0        P101               Wireless Mouse    799     4.3     1520         350
1        P102            Bluetooth Speaker   1499     4.5      980         220
2        P103                 USB Keyboard    699     4.1      870         180
3        P104               Gaming Headset   2499     4.6     2100         410
4        P105                   Smartwatch   3999     4.4     3050         520
5        P106                   Power Bank   1199     4.2     1750         390
6        P107                 Laptop Stand    899     4.0      620         140
7        P108                       Webcam   1899     4.3     1120         260
8        P109                 Portable SSD   5499     4.7     1850         330
9        P110             Wireless Charger    999     4.2      760         190
10       P111  Noise Cancelling Headphones   7999     4.6     4200         610
11       P112          Mechanical Keyboard   4599     4.5     2100         290
12       P113                 Gaming Mouse   1599     4.4     1300         340
13       P114                 Tablet Stand    699     4.1      540         120
14       P115                      USB Hub    899     4.2      870         200
15       P116          External Hard Drive   6499     4.6     2300         310
16       P117            Smartphone Tripod   1199     4.3      760         210
17       P118              Laptop Backpack   1999     4.4     1600         420
18       P119            Bluetooth Earbuds   2999     4.5     3500         530
19       P120                LED Desk Lamp   1299     4.3      980         260
20       P121                 Phone Holder    499     4.0      420         150
21       P122            Wireless Keyboard   2499     4.4     1450         310
22       P123             Portable Monitor   8999     4.6     1250         170
23       P124                   Smart Plug    799     4.2      720         210
24       P125                  WiFi Router   3499     4.5     2100         390
25       P126              Graphics Tablet   4599     4.4      980         160
26       P127                   VR Headset  12999     4.7     3100         140
27       P128                   Microphone   2199     4.3     1300         270
28       P129             Smart Light Bulb    699     4.2      880         240
29       P130           Laptop Cooling Pad   1499     4.3      990         260
30       P131                Action Camera   9999     4.6     2100         200
31       P132               Smart Doorbell   5999     4.5     1750         180
32       P133              Streaming Stick   3499     4.4     2500         430
33       P134           Portable Projector  11999     4.6     1450         120
34       P135                 Gaming Chair  15999     4.7     2100          90
35       P136               Desk Organizer    599     4.1      450         160
36       P137              USB Flash Drive    799     4.2      900         320
37       P138       Phone Screen Protector    299     4.0      600         380
38       P139                Laptop Sleeve    999     4.3      720         210
39       P140           Wireless Presenter   1499     4.4      520         130
40       P141         Tablet Keyboard Case   2999     4.5      850         150
41       P142             Smart Thermostat  10999     4.6     1200         110
42       P143              Security Camera   4999     4.4     2100         260
43       P144                 Drone Camera  24999     4.7     1800          70
44       P145              Electric Kettle   1999     4.3     1400         310
45       P146                    Air Fryer   7999     4.6     2200         200
46       P147                 Robot Vacuum  18999     4.5     1650         120
47       P148                  Smart Scale   2499     4.4      980         170
48       P149          Digital Photo Frame   3499     4.3      870         150
49       P150                 Portable Fan    999     4.2      760         240

In [55]:
# Min - Max Normalisation
# Min - Max Normalisation for Price

df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())
print(df[['Product_ID','Price','Price_MinMax']])

   Product_ID  Price  Price_MinMax
0        P101    799      0.020243
1        P102   1499      0.048583
2        P103    699      0.016194
3        P104   2499      0.089069
4        P105   3999      0.149798
5        P106   1199      0.036437
6        P107    899      0.024291
7        P108   1899      0.064777
8        P109   5499      0.210526
9        P110    999      0.028340
10       P111   7999      0.311741
11       P112   4599      0.174089
12       P113   1599      0.052632
13       P114    699      0.016194
14       P115    899      0.024291
15       P116   6499      0.251012
16       P117   1199      0.036437
17       P118   1999      0.068826
18       P119   2999      0.109312
19       P120   1299      0.040486
20       P121    499      0.008097
21       P122   2499      0.089069
22       P123   8999      0.352227
23       P124    799      0.020243
24       P125   3499      0.129555
25       P126   4599      0.174089
26       P127  12999      0.514170
27       P128   2199      0.076923
28       P129    699      0.016194
29       P130   1499      0.048583
30       P131   9999      0.392713
31       P132   5999      0.230769
32       P133   3499      0.129555
33       P134  11999      0.473684
34       P135  15999      0.635628
35       P136    599      0.012146
36       P137    799      0.020243
37       P138    299      0.000000
38       P139    999      0.028340
39       P140   1499      0.048583
40       P141   2999      0.109312
41       P142  10999      0.433198
42       P143   4999      0.190283
43       P144  24999      1.000000
44       P145   1999      0.068826
45       P146   7999      0.311741
46       P147  18999      0.757085
47       P148   2499      0.089069
48       P149   3499      0.129555
49       P150    999      0.028340

In [56]:
# Normalise Multiple Columns

cols=['Rating','Reviews',	'Units_Sold']
df_norm = (df[cols]-df[cols].min())/(df[cols].max() - df[cols].min())
print(df_norm)

      Rating   Reviews  Units_Sold
0   0.428571  0.291005    0.518519
1   0.714286  0.148148    0.277778
2   0.142857  0.119048    0.203704
3   0.857143  0.444444    0.629630
4   0.571429  0.695767    0.833333
5   0.285714  0.351852    0.592593
6   0.000000  0.052910    0.129630
7   0.428571  0.185185    0.351852
8   1.000000  0.378307    0.481481
9   0.285714  0.089947    0.222222
10  0.857143  1.000000    1.000000
11  0.714286  0.444444    0.407407
12  0.571429  0.232804    0.500000
13  0.142857  0.031746    0.092593
14  0.285714  0.119048    0.240741
15  0.857143  0.497354    0.444444
16  0.428571  0.089947    0.259259
17  0.571429  0.312169    0.648148
18  0.714286  0.814815    0.851852
19  0.428571  0.148148    0.351852
20  0.000000  0.000000    0.148148
21  0.571429  0.272487    0.444444
22  0.857143  0.219577    0.185185
23  0.285714  0.079365    0.259259
24  0.714286  0.444444    0.592593
25  0.571429  0.148148    0.166667
26  1.000000  0.708995    0.129630
27  0.428571  0.232804    0.370370
28  0.285714  0.121693    0.314815
29  0.428571  0.150794    0.351852
30  0.857143  0.444444    0.240741
31  0.714286  0.351852    0.203704
32  0.571429  0.550265    0.666667
33  0.857143  0.272487    0.092593
34  1.000000  0.444444    0.037037
35  0.142857  0.007937    0.166667
36  0.285714  0.126984    0.462963
37  0.000000  0.047619    0.574074
38  0.428571  0.079365    0.259259
39  0.571429  0.026455    0.111111
40  0.714286  0.113757    0.148148
41  0.857143  0.206349    0.074074
42  0.571429  0.444444    0.351852
43  1.000000  0.365079    0.000000
44  0.428571  0.259259    0.444444
45  0.857143  0.470899    0.240741
46  0.714286  0.325397    0.092593
47  0.571429  0.148148    0.185185
48  0.428571  0.119048    0.148148
49  0.285714  0.089947    0.314815

In [57]:
# Z-Score Normalisation

df['Units ZScore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()
print(df[['Product_ID','Units_Sold','Units ZScore']])

   Product_ID  Units_Sold  Units ZScore
0        P101         350      0.812282
1        P102         220     -0.260855
2        P103         180     -0.591051
3        P104         410      1.307576
4        P105         520      2.215615
5        P106         390      1.142478
6        P107         140     -0.921247
7        P108         260      0.069341
8        P109         330      0.647184
9        P110         190     -0.508502
10       P111         610      2.958556
11       P112         290      0.316988
12       P113         340      0.729733
13       P114         120     -1.086345
14       P115         200     -0.425953
15       P116         310      0.482086
16       P117         210     -0.343404
17       P118         420      1.390125
18       P119         530      2.298164
19       P120         260      0.069341
20       P121         150     -0.838698
21       P122         310      0.482086
22       P123         170     -0.673600
23       P124         210     -0.343404
24       P125         390      1.142478
25       P126         160     -0.756149
26       P127         140     -0.921247
27       P128         270      0.151890
28       P129         240     -0.095757
29       P130         260      0.069341
30       P131         200     -0.425953
31       P132         180     -0.591051
32       P133         430      1.472674
33       P134         120     -1.086345
34       P135          90     -1.333992
35       P136         160     -0.756149
36       P137         320      0.564635
37       P138         380      1.059929
38       P139         210     -0.343404
39       P140         130     -1.003796
40       P141         150     -0.838698
41       P142         110     -1.168894
42       P143         260      0.069341
43       P144          70     -1.499090
44       P145         310      0.482086
45       P146         200     -0.425953
46       P147         120     -1.086345
47       P148         170     -0.673600
48       P149         150     -0.838698
49       P150         240     -0.095757

In [58]:
# Decimal Scaling

df['Units_Decimal'] = df['Units_Sold'] / 100
print(df[['Product_ID','Units_Decimal']])

   Product_ID  Units_Decimal
0        P101            3.5
1        P102            2.2
2        P103            1.8
3        P104            4.1
4        P105            5.2
5        P106            3.9
6        P107            1.4
7        P108            2.6
8        P109            3.3
9        P110            1.9
10       P111            6.1
11       P112            2.9
12       P113            3.4
13       P114            1.2
14       P115            2.0
15       P116            3.1
16       P117            2.1
17       P118            4.2
18       P119            5.3
19       P120            2.6
20       P121            1.5
21       P122            3.1
22       P123            1.7
23       P124            2.1
24       P125            3.9
25       P126            1.6
26       P127            1.4
27       P128            2.7
28       P129            2.4
29       P130            2.6
30       P131            2.0
31       P132            1.8
32       P133            4.3
33       P134            1.2
34       P135            0.9
35       P136            1.6
36       P137            3.2
37       P138            3.8
38       P139            2.1
39       P140            1.3
40       P141            1.5
41       P142            1.1
42       P143            2.6
43       P144            0.7
44       P145            3.1
45       P146            2.0
46       P147            1.2
47       P148            1.7
48       P149            1.5
49       P150            2.4

In [59]:
import pandas as pd

df = pd.read_csv('/content/Student-Dataset.csv')
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,Placed,450000
1,102,Male,IT,7.5,1,85,Not Placed,0
2,103,Female,ENTC,9.1,0,96,Placed,550000
3,104,Male,Mechanical,6.8,2,78,Not Placed,0
4,105,Female,Computer,8.7,0,88,Placed,480000
5,106,Male,Civil,7.2,3,72,Not Placed,0
6,107,Female,IT,8.9,0,91,Placed,500000
7,108,Male,Computer,6.5,1,80,Not Placed,0
8,109,Female,ENTC,7.8,0,84,Placed,420000
9,110,Male,Mechanical,7.0,2,76,Not Placed,0

In [60]:
# Label Encoding

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender_Label'] = le.fit_transform(df['Gender'])
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Gender_Label
0,101,Female,Computer,8.2,0,92,Placed,450000,0
1,102,Male,IT,7.5,1,85,Not Placed,0,1
2,103,Female,ENTC,9.1,0,96,Placed,550000,0
3,104,Male,Mechanical,6.8,2,78,Not Placed,0,1
4,105,Female,Computer,8.7,0,88,Placed,480000,0
5,106,Male,Civil,7.2,3,72,Not Placed,0,1
6,107,Female,IT,8.9,0,91,Placed,500000,0
7,108,Male,Computer,6.5,1,80,Not Placed,0,1
8,109,Female,ENTC,7.8,0,84,Placed,420000,0
9,110,Male,Mechanical,7.0,2,76,Not Placed,0,1

In [61]:
# One - Hot Coding

df_encoded = pd.get_dummies(df,columns=['CGPA'])
df_encoded

,Roll_No,Gender,Department,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Gender_Label,CGPA_6.5,CGPA_6.8,CGPA_7.0,CGPA_7.2,CGPA_7.5,CGPA_7.8,CGPA_8.2,CGPA_8.7,CGPA_8.9,CGPA_9.1
0,101,Female,Computer,0,92,Placed,450000,0,False,False,False,False,False,False,True,False,False,False
1,102,Male,IT,1,85,Not Placed,0,1,False,False,False,False,True,False,False,False,False,False
2,103,Female,ENTC,0,96,Placed,550000,0,False,False,False,False,False,False,False,False,False,True
3,104,Male,Mechanical,2,78,Not Placed,0,1,False,True,False,False,False,False,False,False,False,False
4,105,Female,Computer,0,88,Placed,480000,0,False,False,False,False,False,False,False,True,False,False
5,106,Male,Civil,3,72,Not Placed,0,1,False,False,False,True,False,False,False,False,False,False
6,107,Female,IT,0,91,Placed,500000,0,False,False,False,False,False,False,False,False,True,False
7,108,Male,Computer,1,80,Not Placed,0,1,True,False,False,False,False,False,False,False,False,False
8,109,Female,ENTC,0,84,Placed,420000,0,False,False,False,False,False,True,False,False,False,False
9,110,Male,Mechanical,2,76,Not Placed,0,1,False,False,True,False,False,False,False,False,False,False

In [62]:
# Dummy Coding

df_encoded = pd.get_dummies(df,columns=['Attendance_Percentage'],drop_first=True)
df_encoded

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Placement_Status,Salary,Gender_Label,Attendance_Percentage_76,Attendance_Percentage_78,Attendance_Percentage_80,Attendance_Percentage_84,Attendance_Percentage_85,Attendance_Percentage_88,Attendance_Percentage_91,Attendance_Percentage_92,Attendance_Percentage_96
0,101,Female,Computer,8.2,0,Placed,450000,0,False,False,False,False,False,False,False,True,False
1,102,Male,IT,7.5,1,Not Placed,0,1,False,False,False,False,True,False,False,False,False
2,103,Female,ENTC,9.1,0,Placed,550000,0,False,False,False,False,False,False,False,False,True
3,104,Male,Mechanical,6.8,2,Not Placed,0,1,False,True,False,False,False,False,False,False,False
4,105,Female,Computer,8.7,0,Placed,480000,0,False,False,False,False,False,True,False,False,False
5,106,Male,Civil,7.2,3,Not Placed,0,1,False,False,False,False,False,False,False,False,False
6,107,Female,IT,8.9,0,Placed,500000,0,False,False,False,False,False,False,True,False,False
7,108,Male,Computer,6.5,1,Not Placed,0,1,False,False,True,False,False,False,False,False,False
8,109,Female,ENTC,7.8,0,Placed,420000,0,False,False,False,True,False,False,False,False,False
9,110,Male,Mechanical,7.0,2,Not Placed,0,1,True,False,False,False,False,False,False,False,False